FROM node:20-slim AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY index.html ./
COPY server ./server
COPY src ./src
COPY vite.config.ts ./
COPY tsconfig.json ./
COPY tsconfig.node.json ./
COPY tsconfig.server.json ./

RUN npm run build

FROM caddy:2

COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/dist /srv
